2021-05-07 15:32:41,190 INFO: microblog startup [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:35:22,997 INFO: microblog startup [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:35:53,699 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:36:23,152 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:36:46,147 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:36:53,327 ERROR: Exception on /index [GET] [in /opt/homebrew/lib/python3.9/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rdyto1/Projects/freeit_flask/app/routes.py", line 13, in index
    1 // 0
ZeroDivisionError: integer division or modulo by zero
2021-05-07 15:38:29,489 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:39:26,709 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 15:39:31,538 ERROR: Exception on /logout [GET] [in /opt/homebrew/lib/python3.9/site-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/homebrew/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rdyto1/Projects/freeit_flask/app/routes.py", line 37, in logout
    1 // 0
ZeroDivisionError: integer division or modulo by zero
2021-05-07 17:34:15,052 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
2021-05-07 17:34:27,703 INFO: server started up [in /Users/rdyto1/Projects/freeit_flask/app/__init__.py:24]
